server:
  port: 8081

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
  server:
    enable-self-preservation: false